# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

DEPTH  = ../..

include $(DEPTH)/config/autoconf.mk

UIFILES = \
	images/check0.png \
	images/check1.png \
	images/check2.png

SKIN_POSTBOX = \
	common/enigmail-common.css \
	postbox/mac/enigmail.css \
	common/enigmail-html.css \
	images/enigmail-about.svg \
	images/enigmail-logo.png \
	images/ok-sign.svg \
	tb-mac/images/enigEncInactive.png \
	tb-mac/images/enigEncNotOk.png \
	tb-mac/images/enigEncOk.png \
	tb-mac/images/enigSignInactive.png \
	tb-mac/images/enigSignNotOk.png \
	tb-mac/images/enigSignOk.png \
	tb-mac/images/enigSignUnkown.png \
	images/importSuccess.png \
	images/twisty-open.png \
	images/twisty-clsd.png \
	images/spinning-wheel.png \
	tb-mac/images/col-encrypted-signed.png \
	tb-windows/images/enigSignActiveNone.png \
	tb-windows/images/enigSignActivePlus.png \
	tb-windows/images/enigSignActiveMinus.png \
	tb-windows/images/enigSignActiveConflict.png \
	tb-windows/images/enigSignInactiveNone.png \
	tb-windows/images/enigSignInactivePlus.png \
	tb-windows/images/enigSignInactiveMinus.png \
	tb-windows/images/enigSignInactiveConflict.png \
	tb-windows/images/enigSignForceYes.png \
	tb-windows/images/enigSignForceNo.png \
	tb-windows/images/enigEncActiveNone.png \
	tb-windows/images/enigEncActivePlus.png \
	tb-windows/images/enigEncActiveMinus.png \
	tb-windows/images/enigEncActiveConflict.png \
	tb-windows/images/enigEncInactiveNone.png \
	tb-windows/images/enigEncInactivePlus.png \
	tb-windows/images/enigEncInactiveMinus.png \
	tb-windows/images/enigEncInactiveConflict.png \
	tb-windows/images/enigEncForceYes.png \
	tb-windows/images/enigEncForceNo.png \
	images/decrypt-active-18.svg \
	images/decrypt-inactive-18.svg \
	images/encrypt-inactive-18.svg \
	images/encrypt-active-18.svg \
	images/encrypt-disabled-18.svg \
	images/sign-active-18.svg \
	images/sign-disabled-18.svg \
	images/sign-inactive-18.svg \
	images/attach-active-18.svg \
	images/attach-disabled-18.svg \
	images/attach-inactive-18.svg \
	images/warning-16.png \
	images/password-error.svg \
	images/headerProtected-18.svg \
	images/headerUnprotected-18.svg

SKIN_INTERLINK = \
	interlink/enigmail.css \
	common/enigmail-common.css \
	common/enigmail-html.css \
	images/enigmail-about.svg \
	images/enigmail-logo.png \
	images/ok-sign.svg \
	classic-seamonkey/images/enigEncInactive.png \
	classic-seamonkey/images/enigEncNotOk.png \
	classic-seamonkey/images/enigEncOk.png \
	classic-seamonkey/images/enigSignInactive.png \
	classic-seamonkey/images/enigSignNotOk.png \
	classic-seamonkey/images/enigSignOk.png \
	classic-seamonkey/images/enigSignUnkown.png \
	images/importSuccess.png \
	images/twisty-open.png \
	images/twisty-clsd.png \
	images/spinning-wheel.png \
	classic-seamonkey/images/col-encrypted-signed.png \
	tb-windows/images/enigSignActiveNone.png \
	tb-windows/images/enigSignActivePlus.png \
	tb-windows/images/enigSignActiveMinus.png \
	tb-windows/images/enigSignActiveConflict.png \
	tb-windows/images/enigSignInactiveNone.png \
	tb-windows/images/enigSignInactivePlus.png \
	tb-windows/images/enigSignInactiveMinus.png \
	tb-windows/images/enigSignInactiveConflict.png \
	tb-windows/images/enigSignForceYes.png \
	tb-windows/images/enigSignForceNo.png \
	tb-windows/images/enigEncActiveNone.png \
	tb-windows/images/enigEncActivePlus.png \
	tb-windows/images/enigEncActiveMinus.png \
	tb-windows/images/enigEncActiveConflict.png \
	tb-windows/images/enigEncInactiveNone.png \
	tb-windows/images/enigEncInactivePlus.png \
	tb-windows/images/enigEncInactiveMinus.png \
	tb-windows/images/enigEncInactiveConflict.png \
	tb-windows/images/enigEncForceYes.png \
	tb-windows/images/enigEncForceNo.png \
	images/decrypt-inactive-24.svg \
	images/decrypt-active-24.svg \
	images/decrypt-inactive-16.svg \
	images/decrypt-active-16.svg \
	images/encrypt-inactive-24.svg \
	images/encrypt-active-24.svg \
	images/encrypt-disabled-24.svg \
	images/sign-active-24.svg \
	images/sign-disabled-24.svg \
	images/sign-inactive-24.svg \
	images/encrypt-inactive-16.svg \
	images/encrypt-active-16.svg \
	images/encrypt-disabled-16.svg \
	images/sign-active-16.svg \
	images/sign-disabled-16.svg \
	images/sign-inactive-16.svg \
	images/attach-inactive-24.svg \
	images/attach-inactive-16.svg \
	images/attach-disabled-24.svg \
	images/attach-disabled-16.svg \
	images/attach-active-24.svg \
	images/attach-active-16.svg \
	images/warning-16.png \
	images/password-error.svg \
	images/headerProtected-24.svg \
	images/headerUnprotected-24.svg \
	images/headerProtected-16.svg \
	images/headerUnprotected-16.svg


SKIN_PHOTONIC = \
	photonic/enigmail.css \
	common/enigmail-common.css \
	common/enigmail-html.css \
	images/enigmail-about.svg \
	images/enigmail-logo.png \
	images/ok-sign.svg \
	classic-seamonkey/images/enigEncInactive.png \
	classic-seamonkey/images/enigEncNotOk.png \
	classic-seamonkey/images/enigEncOk.png \
	classic-seamonkey/images/enigSignInactive.png \
	classic-seamonkey/images/enigSignNotOk.png \
	classic-seamonkey/images/enigSignOk.png \
	classic-seamonkey/images/enigSignUnkown.png \
	images/importSuccess.png \
	images/twisty-open.png \
	images/twisty-clsd.png \
	images/spinning-wheel.png \
	classic-seamonkey/images/col-encrypted-signed.png \
	tb-windows/images/enigSignActiveNone.png \
	tb-windows/images/enigSignActivePlus.png \
	tb-windows/images/enigSignActiveMinus.png \
	tb-windows/images/enigSignActiveConflict.png \
	tb-windows/images/enigSignInactiveNone.png \
	tb-windows/images/enigSignInactivePlus.png \
	tb-windows/images/enigSignInactiveMinus.png \
	tb-windows/images/enigSignInactiveConflict.png \
	tb-windows/images/enigSignForceYes.png \
	tb-windows/images/enigSignForceNo.png \
	tb-windows/images/enigEncActiveNone.png \
	tb-windows/images/enigEncActivePlus.png \
	tb-windows/images/enigEncActiveMinus.png \
	tb-windows/images/enigEncActiveConflict.png \
	tb-windows/images/enigEncInactiveNone.png \
	tb-windows/images/enigEncInactivePlus.png \
	tb-windows/images/enigEncInactiveMinus.png \
	tb-windows/images/enigEncInactiveConflict.png \
	tb-windows/images/enigEncForceYes.png \
	tb-windows/images/enigEncForceNo.png \
	images/decrypt-inactive-18.svg \
	images/decrypt-active-18.svg \
	images/encrypt-inactive-18.svg \
	images/encrypt-active-18.svg \
	images/encrypt-disabled-16.svg \
	images/sign-active-18.svg \
	images/sign-disabled-18.svg \
	images/sign-inactive-18.svg \
	images/attach-inactive-18.svg \
	images/attach-disabled-18.svg \
	images/attach-active-18.svg \
	images/warning-16.png \
	images/password-error.svg \
	images/headerProtected-18.svg \
	images/headerUnprotected-18.svg

ifeq ($(ENABLE_POSTBOX),yes)
SKIN_INTERLINK =
SKIN_PHOTONIC =
else
SKIN_POSTBOX =
endif

all: deploy

deploy: $(UIFILES) $(SKIN_POSTBOX) $(SKIN_INTERLINK) $(SKIN_PHOTONIC)
	$(DEPTH)/util/install -m 644 $(DIST)/chrome/content/ui $(UIFILES)
	$(DEPTH)/util/install -m 644 $(DIST)/chrome/skin/postbox $(SKIN_POSTBOX)
	$(DEPTH)/util/install -m 644 $(DIST)/chrome/skin/interlink $(SKIN_INTERLINK)
	$(DEPTH)/util/install -m 644 $(DIST)/chrome/skin/photonic $(SKIN_PHOTONIC)
