image: node:13-buster

build:
  script:
    - apt update -y -qq
    - apt install zip -y -qq
    - ./configure
    - make

lint:
  before_script:
    - npm install -g eslint
  script:
    - ./configure
    - make eslint

check:
  script:
    - ./configure
    - make check
