image: node:16-buster

build:
  script:
    - apt update -y -qq
    - apt install zip -y -qq
    - ./configure
    - make

lint:
  before_script:
    - npm install -g eslint
  script:
    - ./configure
    - make eslint

check:
  script:
    - ./configure
    - make check

test:
  before_script:
    - export TBPROFILE="$(pwd)/tb-test-profile"
    - apt update -y -qq
    - apt install thunderbird gnupg zip unzip curl libgtk-3-0 libasound2 xvfb libgpgme11 libassuan-dev -y -qq
    - mkdir -p $TBPROFILE/extensions tmp
    - printf '%s/build-il/dist/' "$(pwd)" > "$TBPROFILE/extensions/{847b3a00-7ab1-11d4-8f02-006008948af5}"
    - printf 'user_pref("extensions.autoDisableScopes", 14);\n' > "$TBPROFILE/prefs.js"
    - printf 'user_pref("browser.dom.window.dump.enabled", true);\n' >> "$TBPROFILE/prefs.js"
    - printf 'user_pref("extensions.update.enabled", false);\n' >> "$TBPROFILE/prefs.js"
    - printf 'user_pref("extensions.update.autoUpdateDefault", false);\n' >> "$TBPROFILE/prefs.js"
    - printf 'user_pref("extensions.blocklist.enabled", false);\n' >> "$TBPROFILE/prefs.js"
    - printf 'user_pref("app.update.enabled", false);\n' >> "$TBPROFILE/prefs.js"
    - printf 'user_pref("app.update.auto", false);\n' >> "$TBPROFILE/prefs.js"
    - printf 'user_pref("extensions.enigmail.logDirectory", "%s");\n' $(pwd)/tmp >> "$TBPROFILE/prefs.js"
    - printf 'user_pref("extensions.enigmail.configuredVersion", "99.0");\n' >> "$TBPROFILE/prefs.js"
    - printf 'user_pref("extensions.enigmail.pEpAutoDownload", false);\n' >> "$TBPROFILE/prefs.js"
    - printf 'user_pref("app.eula.accepted", true);\n' >> "$TBPROFILE/prefs.js"
    - printf 'user_pref("mail.accountmanager.accounts", "account1");\n' >> "$TBPROFILE/prefs.js"
    - printf 'user_pref("mail.account.account1.server", "server1");\n' >> "$TBPROFILE/prefs.js"
    - printf 'user_pref("mail.server.server1.directory-rel", "[ProfD]Mail/Local Folders");\n' >> "$TBPROFILE/prefs.js"
    - printf 'user_pref("mail.server.server1.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");\n' >> "$TBPROFILE/prefs.js"
    - printf 'user_pref("mail.server.server1.type", "none");\n' >> "$TBPROFILE/prefs.js"
    - printf 'user_pref("mail.server.server1.userName", "nobody");\n' >> "$TBPROFILE/prefs.js"
    - printf 'user_pref("mail.server.server1.hostname", "Local Folders");\n' >> "$TBPROFILE/prefs.js"
    - printf 'user_pref("mail.server.server1.name", "Local Folders");\n' >> "$TBPROFILE/prefs.js"
    - printf '{%s "main.js"}\n' '"mainFile":' > "$TBPROFILE/jsunit.json"
    #- export TBDOWNLOAD=$(curl -s 'https://download.mozilla.org/?product=thunderbird-beta-latest&os=linux64&lang=en-US' | sed -E 's/(.*href=")([^"]+)(".*)/\2/')
    - export LIBGPGERR=1.42
    - curl -s -o libgpg-error.tar.bz2 https://gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-1.42.tar.bz2
    - tar jxf libgpg-error.tar.bz2
    - (cd libgpg-error-${LIBGPGERR} && ./configure && make && make install)
    - export GPGMEVERSION=1.15.1
    - curl -s -o gpgme.tar.bz2 https://enigmail.net/unit-testing/gpgme-${GPGMEVERSION}.tar.bz2
    - tar jxf gpgme.tar.bz2
    - (cd gpgme-${GPGMEVERSION} && ./configure && make && make install)
    - export TBDOWNLOAD=https://repository.binaryoutcast.com/projects/interlink/releases/7463/interlink-52.9.7463.linux-x86_64-gtk3.tar.xz
    - curl -s -o interlink.tar.xz $TBDOWNLOAD
    - tar -xJvf interlink.tar.xz
    - interlink/interlink --version
  script:
    - export TBPROFILE="$(pwd)/tb-test-profile"
    - export TMPDIR="$(pwd)/tmp"
    - mkdir -p $TMPDIR
    - export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/
    - export XAUTHORITY="$(pwd)/tmp/.Xauthority"
    - ./configure --enable-tests --with-tb-path=`printf '%s/interlink/interlink' "$(pwd)"` --with-tb-args="--profile $TBPROFILE"
    - make xpi
    - cat config/autoconf.mk
    - ls $TBPROFILE
    - cat $TBPROFILE/prefs.js
    - USER=root xvfb-run -a -f "$XAUTHORITY" $(which make) unit
  artifacts:
    paths:
      - config
      - tmp
      - tb-test-profile

postbox_test:
  before_script:
    - dpkg --add-architecture i386
    - apt update -y -qq
    - apt install thunderbird wine wine32 perl p7zip-full zip unzip curl xvfb libgtk-3-0 -y -qq
    - export POSTBOXDL=https://enigmail.net/unit-testing/Postbox-7.0.15.zip
    - curl -s -o postbox.zip $POSTBOXDL
    - unzip postbox.zip
    - export PERLDL=https://enigmail.net/unit-testing/MiniPerl-5.30.zip
    - curl -o perl.zip $PERLDL
    - unzip perl.zip
    - export GPGDL=https://enigmail.net/unit-testing/gnupg-portable-win32-2.2.17-3.7z
    - curl -o gnupg-inst.7z $GPGDL
    - 7z x -y gnupg-inst.7z
    - provisioning/wine-setup.sh

  script:
    - mkdir tmp
    - export TMPDIR="$(pwd)/tmp"
    - export XAUTHORITY="$(pwd)/tmp/.Xauthority"
    - export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/
    - ./configure --enable-postbox --enable-tests --with-tb-path=$(pwd)/pbx-wrapper.sh
    - make xpi
    - cat config/autoconf.mk
    - USER=root xvfb-run -a -f "$XAUTHORITY" $(which make) unit
  artifacts:
    paths:
      - config
      - tmp
      - tb-test-profile
