#!/bin/sh

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

#
# This script generates the Enigmail XPI
#

echo "prepPackage: Generating pakage files for version $2 in $3"

if [ $# -lt 3 ]; then
  echo "Wrong number of parameters"
  exit 1
fi

tool=$1
enigmailVersion=$2
distDir="$3"

if [ $tool = "tbird" ]; then
  srcfile=manifest.json
  targetFile=manifest.json
elif [ $tool = "pbx" ]; then
  srcfile=install.rdf
  targetFile=install.rdf
else
  srcfile=install-interlink.rdf
  targetFile=install.rdf
fi

sed 's/\${EnigmailVersion}/'${enigmailVersion}'/' < $srcfile > $distDir/$targetFile
